/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { Image } from "./components/fancy-slider/types";
export namespace Components {
    interface FancySlider {
        "images": Image[];
        "initialIndex": number;
    }
}
declare global {
    interface HTMLFancySliderElement extends Components.FancySlider, HTMLStencilElement {
    }
    var HTMLFancySliderElement: {
        prototype: HTMLFancySliderElement;
        new (): HTMLFancySliderElement;
    };
    interface HTMLElementTagNameMap {
        "fancy-slider": HTMLFancySliderElement;
    }
}
declare namespace LocalJSX {
    interface FancySlider {
        "images"?: Image[];
        "initialIndex"?: number;
    }
    interface IntrinsicElements {
        "fancy-slider": FancySlider;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "fancy-slider": LocalJSX.FancySlider & JSXBase.HTMLAttributes<HTMLFancySliderElement>;
        }
    }
}
